name: Apps apply

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  get_changes:
    uses: prefapp/firestarter-workflows/.github/workflows/state-repo-analyze-changes.yaml@main
    with:
      path: 'apps'
      is-app: true

  deploy:
    needs: get_changes
    if: ${{ needs.get_changes.outputs.changes != '[]' && needs.get_changes.outputs.changes != '' }}

    strategy:
      matrix:
        environments: ${{ fromJson(needs.get_changes.outputs.changes) }}

    uses: prefapp/firestarter-workflows/.github/workflows/state-repo-helm-apps.yaml@main
    with:
      apply: true
      config_file: .github/apps-config.yml
      environment: ${{ matrix.environments.name }}
      updated_apps: ${{ toJSON(matrix.environments.changed) }}
      sops_enabled: true